# syntax=docker/dockerfile:1

FROM node:20-alpine AS deps
WORKDIR /app
COPY package*.json ./
RUN npm ci

FROM node:20-alpine AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

ARG NEXT_PUBLIC_API_URL=http://localhost:8080
ARG NEXT_PUBLIC_API_TIMEOUT_MS=10000
ARG NEXT_PUBLIC_LOG_LEVEL=warn
ARG NEXT_PUBLIC_ENABLE_REMOTE_LOGS=false
ARG NEXT_PUBLIC_LOG_INGEST_URL=http://localhost:8080/api/logs/client
ARG NEXT_PUBLIC_REMOTE_LOG_LEVEL=warn
ARG NEXT_PUBLIC_REMOTE_LOG_BATCH_SIZE=20
ARG NEXT_PUBLIC_REMOTE_LOG_FLUSH_MS=5000
ARG NEXT_PUBLIC_REMOTE_LOG_MAX_QUEUE=200
ARG NEXT_PUBLIC_GOOGLE_CLIENT_ID=

ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_API_TIMEOUT_MS=$NEXT_PUBLIC_API_TIMEOUT_MS
ENV NEXT_PUBLIC_LOG_LEVEL=$NEXT_PUBLIC_LOG_LEVEL
ENV NEXT_PUBLIC_ENABLE_REMOTE_LOGS=$NEXT_PUBLIC_ENABLE_REMOTE_LOGS
ENV NEXT_PUBLIC_LOG_INGEST_URL=$NEXT_PUBLIC_LOG_INGEST_URL
ENV NEXT_PUBLIC_REMOTE_LOG_LEVEL=$NEXT_PUBLIC_REMOTE_LOG_LEVEL
ENV NEXT_PUBLIC_REMOTE_LOG_BATCH_SIZE=$NEXT_PUBLIC_REMOTE_LOG_BATCH_SIZE
ENV NEXT_PUBLIC_REMOTE_LOG_FLUSH_MS=$NEXT_PUBLIC_REMOTE_LOG_FLUSH_MS
ENV NEXT_PUBLIC_REMOTE_LOG_MAX_QUEUE=$NEXT_PUBLIC_REMOTE_LOG_MAX_QUEUE
ENV NEXT_PUBLIC_GOOGLE_CLIENT_ID=$NEXT_PUBLIC_GOOGLE_CLIENT_ID

RUN npm run build

FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
ENV PORT=3000
ENV HOSTNAME=0.0.0.0

RUN addgroup -S nodejs && adduser -S nextjs -G nodejs

COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs
EXPOSE 3000
CMD ["node", "server.js"]
